version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: '05:00'
      timezone: Europe/Berlin
      day: friday
  - package-ecosystem: 'pub'
    directory: '/native_image_cropper'
    schedule:
      interval: weekly
      time: '05:00'
      timezone: Europe/Berlin
      day: friday
  - package-ecosystem: 'pub'
    directory: '/native_image_cropper_android'
    schedule:
      interval: weekly
      time: '05:00'
      timezone: Europe/Berlin
      day: friday
  - package-ecosystem: 'pub'
    directory: '/native_image_cropper_ios'
    schedule:
      interval: weekly
      time: '05:00'
      timezone: Europe/Berlin
      day: friday
  - package-ecosystem: 'pub'
    directory: '/native_image_cropper_macos'
    schedule:
      interval: weekly
      time: '05:00'
      timezone: Europe/Berlin
      day: friday
  - package-ecosystem: 'pub'
    directory: '/native_image_cropper_platform_interface'
    schedule:
      interval: weekly
      time: '05:00'
      timezone: Europe/Berlin
      day: friday
  - package-ecosystem: 'pub'
    directory: '/native_image_cropper_web'
    schedule:
      interval: weekly
      time: '05:00'
      timezone: Europe/Berlin
      day: friday
