name: native_image_cropper
description: A new Flutter plugin project.
repository: https://github.com/cosee/native_image_cropper/native_image_cropper_platform_interface
version: 0.0.1


environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
