name: native_image_cropper_platform_interface
description: A common platform interface for the native_image_cropper plugin.
repository: https://github.com/cosee/native_image_cropper/native_image_cropper_platform_interface
homepage: https://pub.dev/publishers/cosee.biz/packages
version: 0.0.1

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  dart_code_metrics: ^5.1.0
