name: native_image_cropper_macos_example
description: Demonstrates how to use the native_image_cropper_macos plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  native_image_cropper_macos:
    # When depending on this package from a real application you should use:
    #   native_image_cropper_macos: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  cupertino_icons: ^1.0.6
  # Saving cropped image to gallery.
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.7.0
  dart_code_linter: ^1.1.3

flutter:
  assets:
    - assets/sail-boat.png
