name: native_image_cropper_example
description: Demonstrates how to use the native_image_cropper plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  native_image_cropper:
    # When depending on this package from a real application you should use:
    #   native_image_cropper: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  image_gallery_saver: ^1.7.1
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.1.4
  dart_code_metrics: ^5.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/sail-boat.png
