name: native_image_cropper_web_example
description: Demonstrates how to use the native_image_cropper_web plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  native_image_cropper_web:
    # When depending on this package from a real application you should use:
    #   native_image_cropper_web: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  file_saver: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.10.0
  dart_code_linter: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sail-boat.png