blank_issues_enabled: false
contact_links:
  - name: Request help
    url: https://github.com/cosee/native_image_cropper/discussions/categories/request-help
    about: Need assistance or guidance with the native_image_cropper plugin? We're here to help!
