name: native_image_cropper_platform_interface_example
description: Demonstrate how to use native_image_cropper_platform_interface.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  native_image_cropper_platform_interface: ^0.2.0

dev_dependencies:
  cosee_lints: ^0.13.0
  dart_code_linter: ^4.0.0
