name: native_image_cropper_platform_interface_example
description: Demonstrate how to use native_image_cropper_platform_interface.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  native_image_cropper_platform_interface:
    # When depending on this package from a real application you should use:
    #   native_image_cropper_platform_interface: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  cosee_lints: ^0.6.0
  dart_code_linter: ^1.1.3
