name: native_image_cropper
description: A Flutter plugin for cropping images. Supports rectangular and circular cropping.
repository: https://github.com/cosee/native_image_cropper/tree/main/native_image_cropper
homepage: https://pub.dev/publishers/cosee.biz/packages
issue_tracker: https://github.com/cosee/native_image_cropper/issues
version: 0.5.0
topics:
  - native
  - crop
  - image-cropper
screenshots:
  - description: 'Default appearance of NativeImageCropper'
    path: 'example/screenshots/default.webp'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: native_image_cropper_android
      ios:
        default_package: native_image_cropper_ios
      macos:
        default_package: native_image_cropper_macos
      web:
        default_package: native_image_cropper_web

dependencies:
  flutter:
    sdk: flutter
  native_image_cropper_android: ^0.2.0
  native_image_cropper_ios: ^0.2.0
  native_image_cropper_macos: ^0.2.0
  native_image_cropper_web: ^0.2.0
  native_image_cropper_platform_interface: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.5.0
  dart_code_metrics: ^5.7.6
