name: native_image_cropper
description: A Flutter plugin for cropping images. Supports rectangular and circular cropping.
repository: https://github.com/cosee/native_image_cropper/native_image_cropper
version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  native_image_cropper: ^0.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

