name: native_image_cropper
description: A Flutter plugin for cropping images. Supports rectangular and circular cropping.
repository: https://github.com/cosee/native_image_cropper/native_image_cropper
homepage: https://pub.dev/publishers/cosee.biz/packages
version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  native_image_cropper_android:
    path: ../native_image_cropper_android
  native_image_cropper_ios:
    path: ../native_image_cropper_ios
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  dart_code_metrics: ^5.1.0

