name: native_image_cropper_ios_example
description: Demonstrates how to use the native_image_cropper_ios plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  native_image_cropper_ios:
    # When depending on this package from a real application you should use:
    #   native_image_cropper_ios: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  cupertino_icons: ^1.0.5
  image_gallery_saver: ^2.0.3
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.3.0
  dart_code_metrics: ^5.7.6

flutter:
  assets:
    - assets/sail-boat.png
