name: native_image_cropper_android
description: This is the Android implementation of the native_image_cropper plugin.
repository: https://github.com/cosee/native_image_cropper/tree/main/native_image_cropper_android
homepage: https://pub.dev/publishers/cosee.biz/packages
issue_tracker: https://github.com/cosee/native_image_cropper/issues
version: 0.3.1

environment:
  sdk: ^3.6.0
  flutter: ^3.3.0

flutter:
  plugin:
    implements: native_image_cropper
    platforms:
      android:
        package: biz.cosee.native_image_cropper
        pluginClass: NativeImageCropperPlugin
        dartPluginClass: NativeImageCropperAndroid

dependencies:
  flutter:
    sdk: flutter
  native_image_cropper_platform_interface: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.9.0
  dart_code_linter: ^2.0.0
