name: native_image_cropper_macos
description: This is the MacOs implementation of the native_image_cropper plugin.
repository: https://github.com/cosee/native_image_cropper/tree/main/native_image_cropper_macos
homepage: https://pub.dev/publishers/cosee.biz/packages
issue_tracker: https://github.com/cosee/native_image_cropper/issues
version: 0.1.1

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: native_image_cropper
    platforms:
      macos:
        pluginClass: NativeImageCropperPlugin
        dartPluginClass: NativeImageCropperMacOS

dependencies:
  flutter:
    sdk: flutter
  native_image_cropper_platform_interface: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.3.0
  dart_code_metrics: ^5.7.6
