name: native_image_cropper_platform_interface

on:
  pull_request:
    paths:
      - 'native_image_cropper_platform_interface/**'
      - '.github/workflows/native_image_cropper_platform_interface.yaml'
  push:
    paths:
      - 'native_image_cropper_platform_interface/**'
      - '.github/workflows/native_image_cropper_platform_interface.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        working-directory: native_image_cropper_platform_interface
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v4
      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf/installs
            ~/.asdf/plugins
            ~/.asdf/shims
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
      - name: Install asdf
        uses: asdf-vm/actions/install@v4
        # See https://github.com/asdf-vm/actions/issues/445
        if: steps.cache-asdf.outputs.cache-hit != 'true'
      - name: Reshim asdf
        run: asdf reshim

      - name: Cache flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            native_image_cropper_platform_interface/.dart_tool/
          key: ${{ runner.os }}-flutter-platform-interface-${{ hashFiles('native_image_cropper_platform_interface/example/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-platform-interface-
      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run code metrics
        run: dart run dart_code_linter:metrics analyze . --set-exit-on-violation-level=warning

  pana:
    defaults:
      run:
        working-directory: native_image_cropper_platform_interface
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v4
      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf/installs
            ~/.asdf/plugins
            ~/.asdf/shims
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
      - name: Install asdf
        uses: asdf-vm/actions/install@v4
        # See https://github.com/asdf-vm/actions/issues/445
        if: steps.cache-asdf.outputs.cache-hit != 'true'
      - name: Reshim asdf
        run: asdf reshim

      - name: Cache flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            native_image_cropper_platform_interface/.dart_tool/
          key: ${{ runner.os }}-flutter-platform-interface-${{ hashFiles('native_image_cropper_platform_interface/example/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-platform-interface-
      - name: Install Dependencies
        run: |
          flutter pub get
          echo $GITHUB_PATH:$HOME/.pub-cache/bin >> $GITHUB_PATH
          flutter pub global activate pana

      - name: Verify Pub Score
        run: ../tool/verify_pub_score.sh
