name: native_image_cropper_platform_interface

on:
  push:
    paths:
      - 'native_image_cropper_platform_interface/**'
      - '.github/workflows/native_image_cropper_platform_interface.yaml'

jobs:
  build:
    defaults:
      run:
        working-directory: native_image_cropper_platform_interface
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache asdf
        uses: actions/cache@v3
        id: asdf_cache
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}
      - uses: asdf-vm/actions/install@v3

      - name: Cache flutter dependencies
        uses: actions/cache@v3
        id: flutter_cache
        with:
          path: native_image_cropper_platform_interface/.dart_tool/
          key: ${{ runner.os }}-platform-interface-${{ hashFiles('**/pubspec.lock') }}
      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run code metrics
        run: dart run dart_code_metrics:metrics analyze . --set-exit-on-violation-level=warning --disable-sunset-warning

  pana:
    defaults:
      run:
        working-directory: native_image_cropper_platform_interface
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache asdf
        uses: actions/cache@v3
        id: asdf_cache
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}
      - uses: asdf-vm/actions/install@v3

      - name: Cache flutter dependencies
        uses: actions/cache@v3
        id: flutter_cache
        with:
          path: |
            native_image_cropper_platform_interface/.dart_tool/
            ~/.pub-cache/
          key: ${{ runner.os }}-platform-interface-${{ hashFiles('**/pubspec.lock') }}
      - name: Install Dependencies
        run: |
          flutter pub get
          echo $GITHUB_PATH:$HOME/.pub-cache/bin >> $GITHUB_PATH
          flutter pub global activate pana

      - name: Verify Pub Score
        run: ../tool/verify_pub_score.sh
