name: native_image_cropper

on:
  push:
    paths:
      - 'native_image_cropper/**'
      - '.github/workflows/native_image_cropper.yaml'

jobs:
  build:
    defaults:
      run:
        working-directory: native_image_cropper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
      - name: Install asdf
        uses: asdf-vm/actions/install@v3
        # See https://github.com/asdf-vm/actions/issues/445
        if: steps.cache-asdf.outputs.cache-hit != 'true'

      - name: Cache flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            native_image_cropper/.dart_tool/
          key: ${{ runner.os }}-flutter-${{ hashFiles('native_image_cropper/example/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-
      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run code metrics
        run: dart run dart_code_linter:metrics analyze . --set-exit-on-violation-level=warning
      - name: Run tests
        run: flutter test

  pana:
    defaults:
      run:
        working-directory: native_image_cropper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
      - name: Install asdf
        uses: asdf-vm/actions/install@v3
        # See https://github.com/asdf-vm/actions/issues/445
        if: steps.cache-asdf.outputs.cache-hit != 'true'

      - name: Install WebP
        run: |
          sudo apt update
          sudo apt install webp
      - name: Cache flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache/
            native_image_cropper/.dart_tool/
          key: ${{ runner.os }}-flutter-${{ hashFiles('native_image_cropper/example/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-
      - name: Install Dependencies
        run: |
          flutter pub get
          echo $GITHUB_PATH:$HOME/.pub-cache/bin >> $GITHUB_PATH
          flutter pub global activate pana

      - name: Verify Pub Score
        run: ../tool/verify_pub_score.sh
