name: native_image_cropper_platform_interface

on:
  push:
    paths:
      - 'native_image_cropper_platform_interface/**'
      - '.github/workflows/native_image_cropper_platform_interface.yaml'

jobs:
  build:
    defaults:
      run:
        working-directory: native_image_cropper_platform_interface
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v2

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: .dart_tool/
          key: ${{ runner.os }}-dependencies-platform-interface-${{ hashFiles('**/pubspec.lock') }}
      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run code metrics
        run: dart run dart_code_metrics:metrics analyze . --set-exit-on-violation-level=warning --disable-sunset-warning

  pana:
    defaults:
      run:
        working-directory: native_image_cropper_platform_interface
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v2

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: .dart_tool/
          key: ${{ runner.os }}-dependencies-platform-interface-${{ hashFiles('**/pubspec.lock') }}
      - name: Install Dependencies
        run: |
          flutter pub get
          flutter pub global activate pana

      - name: Verify Pub Score
        run: ../tool/verify_pub_score.sh
